#!/bin/sh

if [ ! "$1" = "" ] ; then
SHELLSCRIPT=$1
else
SHELLSCRIPT=AutoRun.php phpunit --colors .
fi
# location of the php binary
PHP_BIN=`which php`
# evaluate the absolute path to installation
INSTALLDIR=`echo $0 | sed 's/autorun//g'`

#  prepend the intallation path if not given an absolute path
if [ "$INSTALLDIR" != "" -a "expr index $SHELLSCRIPT /" != "1" ];then
	# Check the process is not already running befor starting it
    if ! ps auxwww | grep "$INSTALLDIR""$CRONSCRIPT" | grep -v grep 1>/dev/null 2>/dev/null ; then
        $PHP_BIN "$INSTALLDIR""$SHELLSCRIPT"
    fi
else
	# Check the process is not already running befor starting it
    if ! ps auxwww | grep " $CRONSCRIPT" | grep -v grep 1>/dev/null 2>/dev/null ; then
        $PHP_BIN $SHELLSCRIPT
    fi
fi